export const LOAD_BALANCES_START = 'LOAD_BALANCES_START';
export const LOAD_BALANCES_SUCCESS = 'LOAD_BALANCES_SUCCESS';
export const LOAD_BALANCES_ERROR = 'LOAD_BALANCES_ERROR';

export const REMOVE_BALANCE_SUCCESS = 'REMOVE_BALANCE_SUCCESS';
export const REMOVE_BALANCE_ERROR = 'REMOVE_BALANCE_ERROR';

export const EDIT_BALANCE = 'EDIT_BALANCE';