export const LOAD_PORTFOLIOS_START = 'LOAD_PORTFOLIOS_START';
export const LOAD_PORTFOLIOS_SUCCESS = 'LOAD_PORTFOLIOS_SUCCESS';
export const LOAD_PORTFOLIOS_ERROR = 'LOAD_PORTFOLIOS_ERROR';

export const CREATE_PORTFOLIO_SUCCESS = 'CREATE_PORTFOLIO_SUCCESS';
export const CREATE_PORTFOLIO_ERROR = 'CREATE_PORTFOLIO_ERROR';

export const EDIT_PORTFOLIO_ERROR = 'EDIT_PORTFOLIO_ERROR';
export const EDIT_PORTFOLIO_SUCCESS = 'EDIT_PORTFOLIO_SUCCESS';

export const REMOVE_PORTFOLIO_ERROR = 'REMOVE_PORTFOLIO_ERROR';
export const REMOVE_PORTFOLIO_SUCCESS = 'REMOVE_PORTFOLIO_SUCCESS';

export const SHOULD_CREATE_PORTFOLIO = 'SHOULD_CREATE_PORTFOLIO';