export const LOAD_TRANSACTIONS_START = 'LOAD_TRANSACTIONS_START';
export const LOAD_TRANSACTIONS_SUCCESS = 'LOAD_TRANSACTIONS_SUCCESS';
export const LOAD_TRANSACTIONS_ERROR = 'LOAD_TRANSACTIONS_ERROR';

export const REMOVE_TRANSACTION_SUCCESS = 'REMOVE_TRANSACTION_SUCCESS';
export const REMOVE_TRANSACTION_ERROR = 'REMOVE_TRANSACTION_ERROR';

export const EDIT_TRANSACTION = 'EDIT_TRANSACTION';