export const LOAD_EXCHANGES_START = 'LOAD_EXCHANGES_START';
export const LOAD_EXCHANGES_SUCCESS = 'LOAD_EXCHANGES_SUCCESS';
export const LOAD_EXCHANGES_ERROR = 'LOAD_EXCHANGES_ERROR';

export const CREATE_USER_STORAGE_START = 'CREATE_USER_STORAGE_START';
export const CREATE_USER_STORAGE_SUCCESS = 'CREATE_USER_STORAGE_SUCCESS';
export const CREATE_USER_STORAGE_ERROR = 'CREATE_USER_STORAGE_ERROR';

export const LOAD_USER_STORAGE_SPACES_START = 'LOAD_USER_STORAGE_SPACES_START';
export const LOAD_USER_STORAGE_SPACES_SUCCESS = 'LOAD_USER_STORAGE_SPACES_SUCCESS';
export const LOAD_USER_STORAGE_SPACES_ERROR = 'LOAD_USER_STORAGE_SPACES_ERROR';