export const LOAD_CRYPTO_DATA_START = 'LOAD_CRYPTO_DATA_START';
export const LOAD_CRYPTO_DATA_SUCCESS = 'LOAD_CRYPTO_DATA_SUCCESS';
export const LOAD_CRYPTO_DATA_ERROR = 'LOAD_CRYPTO_DATA_ERROR';

export const LOAD_MARKET_DATA_START = 'LOAD_MARKET_DATA_START';
export const LOAD_MARKET_DATA_SUCCESS = 'LOAD_MARKET_DATA_SUCCESS';
export const LOAD_MARKET_DATA_ERROR = 'LOAD_MARKET_DATA_ERROR';
